format_version: 10                # pipeline version from gocd, based on this options would vary 
pipelines: 
  backend:                                             # name of the pipeline job that will be showing on UI
    group: Expense-App-Deployment                               # group name to which this pipeline belongs
    label_template: "${COUNT}"                  # label template for the pipeline, ${COUNT} is a predefined variable
    materials:
      Ansible-code:
        git: https://github.com/Shripad13/Ansible.git
        branch: main
        auto_update: true 
        shallow_clone: true                  # perform shallow clone to save time and space
        display_order: -1                    # display order of the material in UI
        lock_behavior: none                  # lock behavior if multiple pipelines are using the same material
    environment_variables:
        COMPONENT: backend
    secure_variables:
        SSH_PWD: "AES:NKYuszy1UK22pl59n0RD7g==:jPTmi+A84fJiNFAnJyrHhw=="
    pipeline: true
    
    stages:
      - dev:
          clean_workspace: false   # clean the workspace before job execution        
          environment_variables:
            ENV: dev
          jobs:
            Build:
              tasks:
                - exec:
                    command: ls
                    arguments: ["-lrth"]
                - exec:
                    command: bash
                    arguments: ["init.sh"]                    


      - qa:
          approval:
            type: manual
            allow_only_on_success: true 
            environment_variables:
              ENV: qa               
          jobs:
            Build:
              tasks:
                - exec:
                    command: ls
                    arguments: ["-lrtah"] 
                - exec:
                    command: bash
                    arguments: ["init.sh"]                                   



      - stage:
          approval:
            type: manual
            allow_only_on_success: true 
            environment_variables:
              ENV: stage                              
          jobs:
            Build:
              tasks:
                - exec:
                    command: ls
                    arguments: ["-lrtah"]
                - exec:
                    command: bash
                    arguments: ["init.sh"]                     
               



      - prod:
          approval:
            type: manual
            allow_only_on_success: true 
            environment_variables:
              ENV: prod                          
          jobs:
            Build:
              tasks:
                - exec:
                    command: ls
                    arguments: ["-lrtah"]
                - exec:
                    command: bash
                    arguments: ["init.sh"]                     
                  