format_version: 10                # pipeline version from gocd, based on this options would vary 
pipelines: 
  expense_terraform_create:                                             # name of the pipeline job that will be showing on UI
    group: Expense-Terraform-App-Deployment                               # group name to which this pipeline belongs
    materials:
      terraform-code:
        git: https://github.com/Shripad13/expense-terraform.git
        branch: main
        auto_update: true 
        shallow_clone: true                  # perform shallow clone to save time and space
        display_order: -1                    # display order of the material in UI
        lock_behavior: none                  # lock behavior if multiple pipelines are using the same material
    secure_variables:
        ssh_pwd: "AES:2OIP4os11Nz8gJ+jtzoUMg==:9RKApCuI7ST7rHEU5UsKuA=="
        vault_token: "AES:0MnF+owJSEFkTnSRpoRm3Q==:XnoIrHIhEi1FmIt2UFmPY8rf+H03P2Pv7VE7SRt4Zus="
    environment_variables:
        action: apply 
    stages:                                       
      - dev:                                       
          fetch_materials: true 
          keep_artifacts: false
          clean_workspace: false
          environment_variables: { env: dev }
          approval: { type: manual }
          jobs:
            terraform:
              tasks:
                - exec: { command: bash, arguments: ["init.sh"] }

      - prod:                                       
          fetch_materials: true 
          keep_artifacts: false
          clean_workspace: false
          environment_variables: { env: prod }
          approval: { type: manual }
          jobs:
            terraform:
              tasks:
                - exec: { command: bash, arguments: ["init.sh"] }   
