format_version: 10               # pipeline version from gocd, based on this options would vary      
pipelines:                      
  App-Deployment-Template:                    # name of the pipeline job that will be showing on UI                                       
    group: Templates                          # group name to which this pipeline belongs
    label_template: "${COUNT}"                # label template for the pipeline, ${COUNT} is a predefined variable
    materials:
      mysql-code:
        git: https://github.com/Shripad13/Ansible.git
        branch: main
        auto_update: true 
        shallow_clone: true                   # perform shallow clone to save time and space
        display_order: -1                     # display order of the material in UI
        lock_behavior: none                   # lock behavior if multiple pipelines are using the same material
    secure_variables:
        SSH_PWD: "AES:NKYuszy1UK22pl59n0RD7g==:jPTmi+A84fJiNFAnJyrHhw=="
    environment_variables:
        pipeline: "true"
    stages:                                       
      - dev:                                       
          fetch_materials: true 
          keep_artifacts: false
          clean_workspace: false
          environment_variables:
            ENV: dev
          secure_variables:
              MYSQL_PSW: "AES:7PQPsFZ2HasPQpLJUeWEMw==:1xTMVEpc9IQHpD36uQON4g==" 
          jobs:
            Build:
              tasks:
                - exec:
                    command: bash 
                    arguments:
                    - init.sh

      - qa:
          approval:
            type: manual
            allow_only_on_success: true
            environment_variables:
              ENV: qa
            secure_variables:
                MYSQL_PSW: "AES:7PQPsFZ2HasPQpLJUeWEMw==:1xTMVEpc9IQHpD36uQON4g==" 
          jobs:
            Build:
              tasks:
                - exec:
                    command: bash 
                    arguments:
                    - init.sh
      - stage:
          approval:
            type: manual
            allow_only_on_success: true
            environment_variables:
              ENV: stage
            secure_variables:
                MYSQL_PSW: "AES:7PQPsFZ2HasPQpLJUeWEMw==:1xTMVEpc9IQHpD36uQON4g==" 
          jobs:
            Build:
              tasks:
                - exec:
                    command: bash 
                    arguments:
                    - init.sh

      - prod:
          fetch_materials: true 
          keep_artifacts: false
          clean_workspace: false 
          environment_variables:
              ENV: prod
          secure_variables:
              MYSQL_PSW: "AES:7PQPsFZ2HasPQpLJUeWEMw==:1xTMVEpc9IQHpD36uQON4g==" 
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            Build:
              tasks:
                - exec:
                    command: bash 
                    arguments:
                    - init.sh   